website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func



class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(15000000000000000))
    category = db.Column(db.String(15000000000000))
    count = db.Column(db.Integer)
    description = db.Column(db.String(100000000000000000000000000000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    products = db.relationship('Product')

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager
from flask import Flask, flash, request, redirect, url_for

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)

    app.config['UPLOAD_EXTENSIONS'] = ['.jpg', '.png', '.gif', 'jpeg']
    app.config['UPLOAD_PATH'] = 'media'
    app.config['SECRET_KEY'] = 'sdfvbnuresdcfvgbhnsdrtybvcxaert'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth


    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')


    from .models import User, Product

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')


website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User, Product
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than three characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than one character.', category='error')
        elif password1 != password2:
            flash('Passwords do not match.', category='error')
        elif len(password1) < 7:
            flash('Password must be greater than six characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign-up.html", user=current_user)

@auth.route('/add-product', methods=['GET', 'POST'])
def add_product():
    if request.method == 'POST':
        name = request.form.get('name')
        category = request.form.get('category')
        count = request.form.get('count')
        description = request.form.get('description')
        if int(count) < 1:
            flash('Minimum stock of the product has to be at least one. Please enter a valid number', category='error')
        elif len(name) < 2:
            flash('Name of product must be greater than one character. Please enter a valid name', category='error')
        elif len(description) < 1:
            flash('There must be a description of the product. Please enter a descrption', category='error')
        elif len(category) < 1:
            flash('The category name must be greater than once character. Please enter a valid category', category='error')
        else:
            new_product = Product(name = name, category=category,  count = count,description = description, user_id = current_user.id)
            db.session.add(new_product)
            db.session.commit()
            flash('Product added!', category='success')
            return redirect(url_for('views.home'))

    return render_template("add-product.html", user=current_user)

@auth.route('/<variable>/update-product', methods=['GET', 'POST'])
def update_product(variable):
    part_to_update = Product.query.get(variable)
    if request.method == 'POST':
        part_to_update.name = request.form.get('name')
        part_to_update.category = request.form.get('category')
        part_to_update.count = request.form.get('count')
        part_to_update.description = request.form.get('description')
        if int(part_to_update.count) < 1:
            flash('Minimum stock of the product has to be at least one. Please enter a valid number', category='error')
        elif len(part_to_update.name) < 2:
            flash('Name of product must be greater than one character. Please enter a valid name', category='error')
        elif len(part_to_update.description) < 1:
            flash('There must be a description of the product. Please enter a descrption', category='error')
        elif len(part_to_update.category) < 1:
            flash('The category name must be greater than once character. Please enter a valid category', category='error')
        else:
 
            db.session.commit()
            flash('Product updated!', category='success')
            return redirect(url_for('views.home'))

    return render_template("update-product.html", user=current_user, products = Product.query.get(variable))


website/views.py
from http.client import HTTPResponse
from itertools import product
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify
from flask_login import login_required, current_user
from .models import Product
from . import db
import json
import csv
from io import StringIO
from flask import make_response
from flask_http_response import success, result, error

views = Blueprint('views', __name__)


@views.route('/')
@login_required

def home():
    return render_template("home.html", user = current_user, products = Product.query.all())
    

@views.route('/delete-product', methods=['POST'])
def delete_product():
    product = json.loads(request.data)
    productId = product['productId']
    product = Product.query.get(productId)
    if product:
        if product.user_id == current_user.id:
            db.session.delete(product)
            db.session.commit()

    return jsonify({})

@views.route('/export-to-csv', methods=['GET','POST'])
def export_to_csv():
    si = StringIO()
    cw = csv.writer(si)
    records = Product.query.all()
    #cw.writerow(['name', 'category','count','description'])
    #for product in Product.objects.all().values_list('name', 'category','count','description'):   
       #cw.writerow(product)
    cw.writerow(['name', 'category','count','description'])
    cw.writerows([(r.name, r.category, r.count, r.description) for r in records])
    response = make_response(si.getvalue())
    response.headers['Content-Disposition'] = 'attachment; filename=data.csv'
    response.headers["Content-type"] = "text/csv"
    return response 
    

website/templates/add-product.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
    content %}
    <form method="POST">
      <h3 align="center">Add Product</h3>
      <div class="form-group">
        <label for="name">Name of Product</label>
        <input
          type="text"
          class="form-control"
          id="name"
          name="name"
          placeholder="Enter name of product"
        />
      </div>
      <div class="form-group">
        <label for="category">Category of product</label>
        <input
          type="text"
          class="form-control"
          id="category"
          name="category"
          placeholder="Enter category of product"
        />
      </div>
      <div class="form-group">
        <label for="count">Count</label>
        <input
          type="number"
          class="form-control"
          id="count"
          name="count"
          placeholder="Enter quantity of the product"
        />
      </div>
      <div class="form-group">
        <label for="description">Description</label>
        <input
          type="text"
          class="form-control"
          id="description"
          name="description"
          placeholder="Enter the product's description"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="addProduct" href="/add-product">Add Product</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
  </body>
</html>

website/templates/file.html
<!doctype html>
<title>Upload Image</title>
<h2>Select a file to upload</h2>
<p>
	{% with messages = get_flashed_messages() %}
	  {% if messages %}
		<ul>
		{% for message in messages %}
		  <li>{{ message }}</li>
		{% endfor %}
		</ul>
	  {% endif %}
	{% endwith %}
</p>
{% if filename %}
	<div>
		<img src="{{ url_for('display_image', filename=filename) }}">
	</div>
{% endif %}
<form method="post" action="/" enctype="multipart/form-data">
    <dl>
		<p>
			<input type="file" name="file" autocomplete="off" required>
		</p>
    </dl>
    <p>
		<input type="submit" value="Submit">
	</p>
</form>

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
    %}
    <h1 align="center">Products</h1>

      <ul class="list-group my-5">
        <li class="list-group-item">
          <div class="container">
            <div class="row">

              <div class="col-sm-2">Name</div>
              <div class="col-sm-2">Category</div>
              <div class="col-sm-2">Count</div>
              <div class="col-sm-2">Description</div>
              <div class = "col-sm-1">Action</div>
            </div>
          </div>
        </li>
        {% for product in products %}
        <li class="list-group-item">
            <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <a href={{url_for('auth.update_product', variable=product.id)}} class="btn btn-primary btn-lg active" role="button" aria-pressed="true">{{product.name}}</a>
                </div>
                <div class="col-sm-2">{{product.category}}</div>
                <div class="col-sm-2">{{product.count}}</div>
                <div class="col-sm-2">{{product.description}}</div>
                <div class = "col-sm-1">
                        {{ product.data }}
                        <button type="button" class="close" onClick="deleteProduct({{ product.id }})">

                            Delete
                          </button>
                </div>
            </div>
            </div>
        </li>
        {%endfor%}
      </ul>
    <br />
    <form action = "{{url_for('views.export_to_csv')}}">
        <input type ="submit" value = "Export to CSV"/>
    </form>
        

 

    {% endblock %}

website/templates/homes.html
@views.route('/')
def upload_form():
	return render_template('file.html')

@views.route('/upload-file', methods=['POST'])
def upload_image():
    if 'file' not in request.files:
        flash('No file part')
        return redirect(request.url)
    file = request.files['file']
    if file.filename == '':
        flash('No image selected for uploading')
        return redirect(request.url)
    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        file.save(os.path.join(views.config['media'], filename))
        flash('Image successfully uploaded and displayed below')
        return render_template('file.html', filename=filename)
    else:
        flash('Allowed image types are -> png, jpg, jpeg, gif')
        return redirect(request.url)

@views.route('/display/<filename>')
def display_image(filename):
	return redirect(url_for('home', filename='uploads/' + filename), code=301)



    si = StringIO()
    cw = csv.writer(si)
    records = Product.query.all()   
    cw.writerows([(r.name, r.category, r.count, r.description) for r in records])
    response = make_response(si.getvalue())
    response.headers['Content-Disposition'] = 'attachment; filename=report.csv'
    response.headers["Content-type"] = "text/csv"
    return render_template("home.html", user = current_user, response = response)

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
    %}
    <form method="POST">
      <h3 align="center">Login</h3>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          placeholder="Enter password"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
    {% endblock %}

website/templates/sign-up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
    content %}
    <form method="POST">
      <h3 align="center">Sign Up</h3>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group">
        <label for="firstName">First Name</label>
        <input
          type="text"
          class="form-control"
          id="firstName"
          name="firstName"
          placeholder="Enter first name"
        />
      </div>
      <div class="form-group">
        <label for="password1">Password</label>
        <input
          type="password"
          class="form-control"
          id="password1"
          name="password1"
          placeholder="Enter password. Makw sure it is at least six characters"
        />
      </div>
      <div class="form-group">
        <label for="password2">Password (Confirm)</label>
        <input
          type="password"
          class="form-control"
          id="password2"
          name="password2"
          placeholder="Confirm password"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endblock %}

website/templates/update-product.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
    content %}
    <form method="POST">
      <h3 align="center">Update Product</h3>
      <div class="form-group">
          {{products.data}}
        <label for="name">Name of Product</label>
        <input
          type="text"
          class="form-control"
          id="name"
          name="name"
          placeholder={{products.name}}
        />
      </div>
      <div class="form-group">
        {{products.data}}
        <label for="category">Category of product</label>
        <input
          type="text"
          class="form-control"
          id="category"
          name="category"
          placeholder={{products.category}}
        />
      </div>
      <div class="form-group">
        {{products.data}}
        <label for="count">Count</label>
        <input
          type="number"
          class="form-control"
          id="count"
          name="count"
          placeholder={{products.count}}
        />
      </div>
      <div class="form-group">
        {{products.data}}
        <label for="description">Description</label>
        <input
          type="text"
          class="form-control"
          id="description"
          name="description"
          placeholder={{products.description}}
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endblock %}